spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: liquibase/change-log-master.yaml
