cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-north-1
    stack:
      auto: false
    s3:
      bucket:
        name:


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB