server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discovery_country
    username: postgres
    password: root

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update